import express from 'express';
import authRoutes from '../../entities/auth/auth.routes.js';
import userRoutes from '../../entities/user/user.routes.js';
import contactRoutes from '../../entities/contact/contact.routes.js';
import caseStudyRoutes from '../../entities/caseStudy/caseStudy.routes.js';
import blogRoutes from '../../entities/blog/blog.routes.js';
import adminDashboardRoutes from '../../entities/adminDashboard/adminDashboard.routes.js';
import careerRoutes from '../../entities/career/career.routes.js';
import careerApplicationRoutes from '../../entities/careerApplication/careerApplication.routes.js';
import realStateRoutes from '../../entities/realState/realState.routes.js';
import servicePageRoutes from '../../entities/servicePage/servicePage.routes.js';
import faqRoutes from '../../entities/faq/faq.routes.js';
import broadcastRoutes from '../../entities/broadcast/broadcast.routes.js';
import { bannerRoutes } from '../../entities/CMS/banner/banner.routes.js';
import { aboutRoutes } from '../../entities/CMS/aboutus/about.routes.js';
import { footerRoutes } from '../../entities/CMS/footer/footer.routes.js';
import { featuresRoutes } from '../../entities/CMS/features/feature.routes.js';
import { statsRoutes } from '../../entities/CMS/stats/stats.routes.js';
import { heroRoutes } from '../../entities/CMS/hero/hero.routes.js';
import { visionRoutes } from '../../entities/CMS/vision/vision.routes.js';
import { informationRoutes } from '../../entities/CMS/information/information.routes.js';
import { consultantRoutes } from '../../entities/CMS/consultant/consultant.routes.js';
import { missionRoutes } from '../../entities/CMS/mission/mission.routes.js';
import { strengthRoutes } from '../../entities/CMS/strength/strength.routes.js';
import { itemsRoutes } from '../../entities/CMS/items/items.routes.js';
import { certificationRoutes } from '../../entities/CMS/certifications/certification.routes.js';
import { expertiseRoutes } from '../../entities/CMS/expertise/expertise.routes.js';
import { applicationRoutes } from '../../entities/application/application.routes.js';
import { transformRoutes } from '../../entities/CMS/transform/transform.routes.js';
import { numberRoutes } from '../../entities/CMS/number/number.routes.js';
import { navbarRoutes } from '../../entities/CMS/navbar/navbar.routes.js';
import { logoRoutes } from '../../entities/CMS/logo/logo.routes.js';
import { servicePageTitleRoutes } from '../../entities/CMS/servicePageTitle/servicePageTitle.routes.js';
import { insightRoutes } from '../../entities/CMS/insight/insight.routes.js';
import { careerTitleRoutes } from '../../entities/CMS/careerTitle/careerTitle.routes.js';
import { serviceTitleRoutes } from '../../entities/CMS/serviceTitle/serviceTitle.routes.js';
import { subscriberTitleRoutes } from '../../entities/CMS/subscriberTitle/subscriberTitle.routes.js';
import { faqNewRoutes } from '../../entities/CMS/faqnew/faqnew.routes.js';
const router = express.Router();


router.use('/v1/auth', authRoutes);
router.use('/v1/contact', contactRoutes);
router.use('/v1/user', userRoutes);
router.use('/v1/case-study', caseStudyRoutes);
router.use('/v1/blog', blogRoutes);
router.use('/v1/admin-dashboard', adminDashboardRoutes);
router.use('/v1/career', careerRoutes);
router.use('/v1/career-application', careerApplicationRoutes);
router.use('/v1/real-state', realStateRoutes);
router.use('/v1/service-page', servicePageRoutes);
router.use('/v1/faq', faqRoutes);
router.use('/v1/broadcast', broadcastRoutes);
router.use('/v1/banner', bannerRoutes);
router.use('/v1/about', aboutRoutes);
router.use('/v1/footer', footerRoutes);
router.use("/v1/features", featuresRoutes);
router.use("/v1/stats", statsRoutes);
router.use("/v1/hero", heroRoutes);
router.use('/v1/vision', visionRoutes);
router.use('/v1/information', informationRoutes);
router.use('/v1/consultant', consultantRoutes);
router.use('/v1/mission', missionRoutes);
router.use('/v1/strength', strengthRoutes);
router.use('/v1/items', itemsRoutes);
router.use('/v1/certifications', certificationRoutes);
router.use('/v1/expertise', expertiseRoutes);
router.use('/v1/application', applicationRoutes);
router.use("/v1/transform", transformRoutes);
router.use('/v1/number', numberRoutes);
router.use('/v1/navbar', navbarRoutes);
router.use('/v1/logo', logoRoutes);
router.use('/v1/service-page-title', servicePageTitleRoutes);
router.use('/v1/insight', insightRoutes);
router.use('/v1/career-title', careerTitleRoutes);
router.use('/v1/service', serviceTitleRoutes);
router.use('/v1/subscriber', subscriberTitleRoutes);
router.use('/v1/faq-new', faqNewRoutes);

export default router;
